alttext = {
    0: "They're in the shopping bag and that's where they're staying.",
    1: "Beaks are terrible on capacitive screens. It's a little known fact that this is intentional.",
    2: "That's a quadrapalegic wheelchair in panel 2. Sad story.",
    3: "Pro-lyme disease commit messages disgust me.",
    4: "They're all underage",
    5: "This could almost be artsy if it weren't for the face in panel 1.",
    6: "That is a terrible black power salute. Straighten your arm out for christ's sake.",
    7: "Well something's certainly more rigid.",
    8: "Or there would be if I hadn't forgotten to `git add`",
    9: "Wow, web 2.0 is starting to look really lifelike.",
    10: "Panel 3 doesn't approve of this satiristic bullcrap",
    11: "That's an order",
    12: "Not sure if that's great under-nail hygene or just a too much gaussian blur",
    13: "I like to imagine panel 2 is saying it like 'nigga please' except he's reading your code",
    14: "It knows what it did",
    15: "Something something something Holden Caulfield",
    16: "I'm pretty sure that's upside down water in panel3. That's not supposed to happen, is it?",
    17: "What a terrible set of images for an awesome commit message",
    18: "I still refuse to change my scroll direction. 'Native' my ass. ",
    19: "blur blur BIRD",
    20: "Bug #12816: SSL key exchange is difficult to carry out using carrier pigeons and an abacus. Please fix.",
    21: "Looks something like this, actually",
    22: "Panel 2 wishes he had hair like that. Daaamn",
    23: "To install tox, use pip install tox, to install pip, use easy_install pip, to install easy_install...",
    24: "Manually fixing merge conflicts in binary files can take a while.",
    25: "Mongodb: Not really scaleable, not really relational. What more could you want?",
    26: "One of these three characters is the murderer. It's Clue: Aviary Edition",
    27: "Does panel2 look like a Goya painting to anyone else?",
    28: "Sadder than Hamlet",
    29: "They don't even look the same",
    30: "Gettin' JSON all gussied up. {} Look at those frills.",
    31: "PDE = Periodontal Devestation Event. This is from a git repository for ruining your gums",
    32: "Well, it's not very secret now that you've told everyone. Nice going.",
    33: "I to_x and from_x methods give preferential treatment to certain preopsitions. Where's the betwixt_string, or atop_string?",
    34: "Using offset-down causes a kernel panic 98% of the time. The other 2% are cotton candy. Happy gambling",
    35: "You can bring a tweet up to 220 grit with an orbital sander, but using handplanes and a buffing wheel will get you much better results",
    36: "Things I have learned: Nearly all github commits over 4 words long begin with'merge pull request...'",
    37: "If we're orphans, call sob_quietly()",
    38: "Hey, at least it's not ie6",
    39: "I have like, 50 repos in here, and it seems like there are only commit messages from 3 of them",
    40: "This one just looks nice",
    41: "What a weird sentence to anyone who's never programmed",
    42: "I'm pretty sure this is from a twitter+arduino project",
    43: "mongodb passengers still mandatory",
    44: "I've  been signing my checks wrong for weeks",
    45: "Workers will be killed if office temperature exceeds 140 degrees. Again.",
    46: "does 'exposing an API' sound a little dirty to anyone else?",
    47: "I'd like to imagine this message is referring to rocket stages.",
    48: "Even more boring than it sounds",
    49: "This is why you unit-test, folks",
    50: "When static, I usually just get a little shock when I touch the doorknob",
    51: "Is writing on a squirell animal cruelty?",
    52: "I feel like this is what commit messages would look like for textbook editions",
    53: "The system is going down for reboot NOW",
    54: "Everyone thinks they'll look cooler in a hat than they actually do"
};